/// Flutter icons IconsRPG
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconsRPG
///      fonts:
///       - asset: fonts/IconsRPG.ttf
///
///
///
import 'package:flutter/widgets.dart';

class IconsRPG {
  IconsRPG._();

  static const _kFontFam = 'IconsRPG';
  static const String? _kFontPkg = null;

  static const IconData backpack = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData weapons = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dwarf = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData purse = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData equipment = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
