/// Flutter icons IconsDices
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconsDices
///      fonts:
///       - asset: fonts/IconsDices.ttf
///
///
///
library;
import 'package:flutter/widgets.dart';

class IconsDices {
  IconsDices._();

  static const _kFontFam = 'IconsDices';

  static const IconData dice4 = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData dice6 = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData dice6_2 = IconData(0xe802, fontFamily: _kFontFam);
}
