import 'package:flutter/material.dart';
import 'package:terre_de_fangh/src/ui/assets/images.dart';

ImageProvider<Object> imageArmors = const AssetImage(AssetsImages.backgroundArmors);
ImageProvider<Object> imageBackpack = const AssetImage(AssetsImages.backgroundBackpack);
ImageProvider<Object> imageBooks = const AssetImage(AssetsImages.backgroundBooks);
ImageProvider<Object> imageCamping = const AssetImage(AssetsImages.backgroundCamping);
ImageProvider<Object> imageDice = const AssetImage(AssetsImages.backgroundCreateCharacter);
ImageProvider<Object> imageFight = const AssetImage(AssetsImages.backgroundFight);
ImageProvider<Object> imageMain = const AssetImage(AssetsImages.backgroundMain);
ImageProvider<Object> imageObjects = const AssetImage(AssetsImages.backgroundObjects);
ImageProvider<Object> imagePotions = const AssetImage(AssetsImages.backgroundPotion);
ImageProvider<Object> imagePouch = const AssetImage(AssetsImages.backgroundPouch);
ImageProvider<Object> imageSkills = const AssetImage(AssetsImages.backgroundSkills);
ImageProvider<Object> imageStatistics = const AssetImage(AssetsImages.backgroundStatistics);
ImageProvider<Object> imageTreasures = const AssetImage(AssetsImages.backgroundTreasures);
ImageProvider<Object> imageWeapons = const AssetImage(AssetsImages.backgroundWeapons);
ImageProvider<Object> imageCharacters = const AssetImage(AssetsImages.backgroundCharacters);
ImageProvider<Object> imageAdventures = const AssetImage(AssetsImages.backgroundAdventures);
ImageProvider<Object> imageAdventuresSolo = const AssetImage(AssetsImages.backgroundAdventuresSolo);
ImageProvider<Object> imageWeb = const AssetImage(AssetsImages.backgroundWeb);
